apiVersion: apps/v1
kind: Deployment
metadata:
  name: articulation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: articulation-app
  template:
    metadata:
      labels:
        app: articulation-app
    spec:
      containers:
      - name: articulation-app
        image: 11112002/articulation-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: articulation-app
spec:
  selector:
    app: articulation-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
