export {default as ForumPage} from './Forum'
export {default as HomePage} from './Home'
export {default as ParentPage} from './Parents'
export {default as SpeechTherapistPage} from './SpeechTherapist'
export {default as RegisterPage} from './Register'
export {default as NotFoundPage} from './NotFound'
export {default as ProfilePage} from './Profile'
export {default as AddPostPage} from './AddPost'
